# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
- group: apiKeys
- name: buildConfiguration
  value: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'
  
- task: VSTest@3
  displayName: 'Test'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **/bin/$(buildConfiguration)/**/SubstituteQueryable.Test.dll
      !**/obj/*
    codeCoverageEnabled: true
    rerunFailedTests: true
  
- script: dotnet pack SubstituteQueryable/SubstituteQueryable.csproj --configuration $(buildConfiguration) --output .
  displayName: 'Nuget Pack'
  
- script: dotnet nuget push *.nupkg --api-key $(nuGetApiKey) --source https://api.nuget.org/v3/index.json
  displayName: 'NuGet Publish'